/* ────────────────────────────────────────────────────────────
   Future Systems Atlas — Data
   Sectors, chemicals, unit ops, bottlenecks, and 115 entries.
   ──────────────────────────────────────────────────────────── */

window.FSA = (() => {
  const SECTORS = [
    { id: "energy",        label: "Energy",        coord: "07°N",  count: 0 },
    { id: "carbon",        label: "Carbon",        coord: "19°N",  count: 0 },
    { id: "water",         label: "Water",         coord: "24°N",  count: 0 },
    { id: "materials",     label: "Materials",     coord: "33°N",  count: 0 },
    { id: "manufacturing", label: "Manufacturing", coord: "41°N",  count: 0 },
    { id: "cities",        label: "Cities",        coord: "48°N",  count: 0 },
    { id: "space",         label: "Space",         coord: "57°N",  count: 0 },
  ];

  const CHEMICALS = [
    { sym: "H₂",  num: "01", name: "Hydrogen",       group: "energy carrier",   uses: ["fuels", "ammonia", "steel", "storage"], color: "energy" },
    { sym: "CO₂", num: "02", name: "Carbon dioxide", group: "carbon spine",     uses: ["DAC", "fuels", "concrete", "polymers"], color: "carbon" },
    { sym: "NH₃", num: "03", name: "Ammonia",        group: "nitrogen carrier", uses: ["fertilizer", "fuels", "shipping", "storage"], color: "energy" },
    { sym: "Si",  num: "14", name: "Silicon",        group: "semiconductor",    uses: ["solar", "ICs", "sensors", "MEMS"], color: "materials" },
    { sym: "Li",  num: "03", name: "Lithium",        group: "alkali metal",     uses: ["batteries", "ceramics", "alloys"], color: "manufacturing" },
    { sym: "Cu",  num: "29", name: "Copper",         group: "transition",       uses: ["motors", "grids", "wiring", "catalysts"], color: "cities" },
    { sym: "H₂O", num: "—",  name: "Water",          group: "utility",          uses: ["purification", "desal", "AWH", "life support"], color: "water" },
    { sym: "C*",  num: "06", name: "Carbon (eng.)",  group: "structural",       uses: ["composites", "anodes", "fibers", "biochar"], color: "materials" },
    { sym: "CH₄", num: "—",  name: "Methane",        group: "C1 building",      uses: ["pyrolysis", "syngas", "biogas"], color: "carbon" },
    { sym: "He",  num: "02", name: "Helium",         group: "noble",            uses: ["cryo", "MRI", "fusion"], color: "space" },
    { sym: "U",   num: "92", name: "Uranium",        group: "fissile",          uses: ["SMR", "fuel cycle"], color: "energy" },
    { sym: "T",   num: "—",  name: "Tritium",        group: "fusion fuel",      uses: ["DT fusion", "breeding blankets"], color: "energy" },
    { sym: "Pt",  num: "78", name: "Platinum",       group: "PGM catalyst",     uses: ["electrolysis", "fuel cells"], color: "manufacturing" },
    { sym: "Ni",  num: "28", name: "Nickel",         group: "transition",       uses: ["cathodes", "alloys", "catalysts"], color: "manufacturing" },
    { sym: "Co",  num: "27", name: "Cobalt",         group: "transition",       uses: ["cathodes", "catalysts"], color: "manufacturing" },
    { sym: "RE",  num: "57+",name: "Rare earths",    group: "lanthanide",       uses: ["magnets", "motors", "lasers"], color: "space" },
  ];

  const UNIT_OPS = [
    { id: "separation",  label: "Separation",  family: "matter movement",    examples: "membranes · distillation · adsorption · crystallization" },
    { id: "reaction",    label: "Reaction",    family: "transformation",      examples: "catalysis · electrolysis · photochemistry · pyrolysis" },
    { id: "heat",        label: "Heat transfer", family: "energy movement",   examples: "exchangers · regenerators · thermal storage" },
    { id: "deposition",  label: "Deposition",  family: "interface control",   examples: "CVD · ALD · PVD · electroplating" },
    { id: "fabrication", label: "Fabrication", family: "shape & assembly",    examples: "additive · roll-to-roll · injection · joining" },
    { id: "qa",          label: "QA · cycling", family: "manufacturing proof", examples: "metrology · reliability · process windows" },
  ];

  const BOTTLENECKS = [
    { id: "energy-intensity", label: "Energy intensity",      family: "thermodynamic" },
    { id: "separations",      label: "Dilute separations",    family: "matter movement" },
    { id: "yield",            label: "Yield & selectivity",    family: "reaction" },
    { id: "reliability",      label: "Reliability / cycles",   family: "manufacturing proof" },
    { id: "supply",           label: "Supply chain",          family: "material limit" },
    { id: "infrastructure",   label: "Infrastructure",        family: "deployment" },
    { id: "cost",             label: "Capex & cost-down",     family: "economics" },
    { id: "safety",           label: "Safety & containment",  family: "operational" },
    { id: "scale-up",         label: "Scale-up reactor",      family: "engineering" },
    { id: "integration",      label: "System integration",    family: "deployment" },
    { id: "regulation",       label: "Regulation & standards",family: "policy" },
    { id: "purity",           label: "Trace purity control",  family: "process window" },
  ];

  const STACK = [
    { id: "resources",      label: "Resources",            sub: "primary feedstocks · land · water · ores · waste streams", nodes: ["bauxite", "brines", "biomass", "feed gas", "scrap", "air", "seawater"] },
    { id: "chemicals",      label: "Platform chemicals",   sub: "molecular building blocks", nodes: ["H₂", "CO₂", "NH₃", "olefins", "syngas", "salts"] },
    { id: "unit-ops",       label: "Unit operations",      sub: "reactors · separations · coatings · deposition · QA", nodes: ["electrolysis", "membranes", "CVD", "distillation", "crystallization"] },
    { id: "manufacturing",  label: "Manufacturing systems", sub: "process windows · reliability · throughput", nodes: ["roll-to-roll", "additive", "wafer fabs", "biofermentation"] },
    { id: "infrastructure", label: "Infrastructure",       sub: "utilities · grids · logistics · standards · safety", nodes: ["grid", "pipelines", "ports", "permits", "service"] },
    { id: "deployable",     label: "Deployable systems",   sub: "products in the built world", nodes: ["vehicles", "buildings", "power plants", "habitats", "appliances"] },
  ];

  const PATHWAYS = [
    "Increase yield per pass",  "Close recycle loops",  "Reduce energy intensity",
    "Tighten process windows",  "Substitute supply-constrained inputs", "Cut capital intensity",
    "Improve reliability cycling","Standardize interfaces", "Modularize for replication",
    "Co-locate utilities & feedstocks", "Drive cost-of-quality down",
  ];

  /* ── 115 atlas entries ──────────────────────────────────── */
  const RAW = [
    // ENERGY (17)
    ["Solid-state batteries", "energy", "Li", "deposition", "purity", "roadmap"],
    ["Sodium-ion batteries", "energy", "Si", "fabrication", "reliability", "direct"],
    ["Iron–air batteries", "energy", "C*", "reaction", "cost", "direct"],
    ["Lithium–sulfur batteries", "energy", "Li", "reaction", "reliability", "roadmap"],
    ["Solid-oxide fuel cells", "energy", "Pt", "deposition", "reliability", "direct"],
    ["Green hydrogen electrolysis", "energy", "H₂", "reaction", "energy-intensity", "direct"],
    ["High-temperature SMR hydrogen", "energy", "H₂", "reaction", "purity", "direct"],
    ["Closed-loop geothermal", "energy", "H₂O", "heat", "scale-up", "roadmap"],
    ["Enhanced geothermal systems", "energy", "H₂O", "heat", "infrastructure", "roadmap"],
    ["Tokamak fusion", "energy", "T", "qa", "scale-up", "analogue"],
    ["Inertial confinement fusion", "energy", "T", "qa", "scale-up", "analogue"],
    ["Stellarator fusion", "energy", "T", "fabrication", "scale-up", "analogue"],
    ["Floating offshore wind", "energy", "Cu", "fabrication", "infrastructure", "direct"],
    ["Airborne wind energy", "energy", "Cu", "fabrication", "reliability", "analogue"],
    ["Perovskite tandem PV", "energy", "Si", "deposition", "reliability", "roadmap"],
    ["Concentrating solar thermal", "energy", "H₂O", "heat", "cost", "direct"],
    ["Tidal stream energy", "energy", "Cu", "fabrication", "reliability", "direct"],

    // CARBON (16)
    ["Liquid-solvent DAC", "carbon", "CO₂", "separation", "energy-intensity", "direct"],
    ["Solid-sorbent DAC", "carbon", "CO₂", "separation", "energy-intensity", "direct"],
    ["Ocean alkalinity enhancement", "carbon", "CO₂", "reaction", "regulation", "roadmap"],
    ["Enhanced rock weathering", "carbon", "CO₂", "reaction", "scale-up", "roadmap"],
    ["Biochar at scale", "carbon", "C*", "reaction", "supply", "direct"],
    ["Mineralized concrete (CO₂-cured)", "carbon", "CO₂", "reaction", "integration", "direct"],
    ["H₂-DRI carbon-negative steel", "carbon", "H₂", "reaction", "infrastructure", "roadmap"],
    ["Synthetic e-kerosene", "carbon", "CO₂", "reaction", "cost", "roadmap"],
    ["e-Methanol", "carbon", "CO₂", "reaction", "cost", "direct"],
    ["CO₂-to-polymers", "carbon", "CO₂", "reaction", "yield", "roadmap"],
    ["Methane pyrolysis", "carbon", "CH₄", "reaction", "yield", "roadmap"],
    ["Mineral carbonation", "carbon", "CO₂", "reaction", "scale-up", "direct"],
    ["Marine CO₂ removal", "carbon", "CO₂", "separation", "regulation", "analogue"],
    ["BECCS", "carbon", "C*", "separation", "supply", "direct"],
    ["Industrial flue capture", "carbon", "CO₂", "separation", "cost", "direct"],
    ["Cement clinker substitution", "carbon", "C*", "reaction", "integration", "direct"],

    // WATER (14)
    ["Atmospheric water (sorbent)", "water", "H₂O", "separation", "energy-intensity", "roadmap"],
    ["Atmospheric water (cooled)", "water", "H₂O", "heat", "energy-intensity", "direct"],
    ["Solar-thermal desalination", "water", "H₂O", "separation", "cost", "direct"],
    ["Membrane distillation", "water", "H₂O", "separation", "reliability", "roadmap"],
    ["Forward osmosis", "water", "H₂O", "separation", "purity", "roadmap"],
    ["Capacitive deionization", "water", "H₂O", "separation", "scale-up", "roadmap"],
    ["Electrochemical PFAS destruction", "water", "H₂O", "reaction", "yield", "roadmap"],
    ["Direct lithium extraction", "water", "Li", "separation", "yield", "roadmap"],
    ["Produced water reuse", "water", "H₂O", "separation", "purity", "direct"],
    ["Greywater closed-loop", "water", "H₂O", "separation", "integration", "direct"],
    ["Fog harvesting", "water", "H₂O", "separation", "supply", "analogue"],
    ["Hypersaline brine valorization", "water", "Li", "reaction", "cost", "roadmap"],
    ["Seawater uranium extraction", "water", "U", "separation", "yield", "analogue"],
    ["Membrane-less electrolytic purification", "water", "H₂O", "reaction", "reliability", "analogue"],

    // MATERIALS (18)
    ["Mycelium structural composites", "materials", "C*", "fabrication", "reliability", "roadmap"],
    ["Self-healing concrete", "materials", "C*", "reaction", "reliability", "roadmap"],
    ["Programmable metamaterials", "materials", "Si", "fabrication", "scale-up", "analogue"],
    ["Topological photonic crystals", "materials", "Si", "deposition", "yield", "analogue"],
    ["Transparent aluminum (AlON)", "materials", "C*", "fabrication", "cost", "direct"],
    ["PHA bioplastics", "materials", "C*", "reaction", "yield", "direct"],
    ["Living building materials", "materials", "C*", "reaction", "regulation", "roadmap"],
    ["Mass-timber CLT", "materials", "C*", "fabrication", "supply", "direct"],
    ["Graphene mass manufacturing", "materials", "C*", "deposition", "yield", "roadmap"],
    ["Cubic boron arsenide thermal", "materials", "Si", "deposition", "scale-up", "analogue"],
    ["Aerogels (silica/polyimide)", "materials", "Si", "fabrication", "cost", "direct"],
    ["Metal-organic frameworks", "materials", "Cu", "reaction", "scale-up", "roadmap"],
    ["Quantum-dot displays", "materials", "Si", "deposition", "purity", "direct"],
    ["Solid-state electrolytes", "materials", "Li", "deposition", "purity", "roadmap"],
    ["Cathode active material recycling", "materials", "Ni", "separation", "supply", "direct"],
    ["Rare-earth-free permanent magnets", "materials", "RE", "fabrication", "supply", "roadmap"],
    ["Photonic neuromorphic chips", "materials", "Si", "deposition", "yield", "analogue"],
    ["Diamond semiconductors", "materials", "C*", "deposition", "scale-up", "analogue"],

    // MANUFACTURING (16)
    ["3D-printed buildings", "manufacturing", "C*", "fabrication", "reliability", "direct"],
    ["Vat photopolymerization at scale", "manufacturing", "C*", "fabrication", "yield", "direct"],
    ["Cold-spray additive", "manufacturing", "Cu", "deposition", "reliability", "direct"],
    ["Continuous-flow chemistry", "manufacturing", "CO₂", "reaction", "scale-up", "direct"],
    ["Modular nuclear factories", "manufacturing", "U", "qa", "regulation", "roadmap"],
    ["Roll-to-roll perovskite", "manufacturing", "Si", "deposition", "yield", "roadmap"],
    ["Lab-grown meat bioreactors", "manufacturing", "C*", "reaction", "cost", "roadmap"],
    ["Cellular agriculture (dairy)", "manufacturing", "C*", "reaction", "cost", "direct"],
    ["Mycelium leather", "manufacturing", "C*", "fabrication", "reliability", "direct"],
    ["Precision fermentation proteins", "manufacturing", "C*", "reaction", "yield", "direct"],
    ["Spider-silk fibers", "manufacturing", "C*", "fabrication", "scale-up", "roadmap"],
    ["Digital twins for fabs", "manufacturing", "Si", "qa", "integration", "direct"],
    ["Co-bot assembly cells", "manufacturing", "Cu", "qa", "integration", "direct"],
    ["Self-assembling materials", "manufacturing", "Si", "deposition", "yield", "analogue"],
    ["Closed-loop battery recycling", "manufacturing", "Li", "separation", "yield", "direct"],
    ["Atomic-layer manufacturing", "manufacturing", "Si", "deposition", "yield", "roadmap"],

    // CITIES (17)
    ["Vertical farms", "cities", "H₂O", "fabrication", "cost", "direct"],
    ["Cultivated produce greenhouses", "cities", "H₂O", "heat", "cost", "direct"],
    ["Urban air mobility (eVTOL)", "cities", "Cu", "qa", "regulation", "roadmap"],
    ["Hyperloop", "cities", "Cu", "fabrication", "infrastructure", "analogue"],
    ["Autonomous transit pods", "cities", "Cu", "qa", "regulation", "roadmap"],
    ["Smart-glass facades", "cities", "Si", "deposition", "cost", "direct"],
    ["Building-integrated PV", "cities", "Si", "deposition", "integration", "direct"],
    ["District geothermal", "cities", "H₂O", "heat", "infrastructure", "direct"],
    ["Sewage-thermal recovery", "cities", "H₂O", "heat", "integration", "direct"],
    ["Smart water grids", "cities", "H₂O", "qa", "integration", "direct"],
    ["Underground freight", "cities", "Cu", "fabrication", "infrastructure", "analogue"],
    ["Robotic last-mile delivery", "cities", "Cu", "qa", "regulation", "direct"],
    ["Microgrids + V2G", "cities", "Cu", "qa", "integration", "direct"],
    ["Heat-pump retrofits at scale", "cities", "Cu", "heat", "supply", "direct"],
    ["Cooling-as-a-service", "cities", "H₂O", "heat", "integration", "direct"],
    ["Urban DAC integration", "cities", "CO₂", "separation", "integration", "roadmap"],
    ["Modular timber towers", "cities", "C*", "fabrication", "regulation", "direct"],

    // SPACE (17)
    ["Reusable super-heavy launch", "space", "CH₄", "qa", "reliability", "direct"],
    ["Methalox propulsion", "space", "CH₄", "reaction", "reliability", "direct"],
    ["Lunar regolith ISRU", "space", "H₂O", "reaction", "scale-up", "roadmap"],
    ["Mars ISRU (Sabatier)", "space", "CO₂", "reaction", "reliability", "roadmap"],
    ["Asteroid mining", "space", "Ni", "fabrication", "infrastructure", "analogue"],
    ["Orbital solar power", "space", "Si", "fabrication", "scale-up", "analogue"],
    ["Active debris removal", "space", "Cu", "qa", "regulation", "roadmap"],
    ["Cislunar fuel depots", "space", "H₂", "qa", "infrastructure", "roadmap"],
    ["Rotating space habitats", "space", "Cu", "fabrication", "scale-up", "analogue"],
    ["Lunar nuclear power", "space", "U", "qa", "regulation", "roadmap"],
    ["On-orbit manufacturing", "space", "Si", "fabrication", "scale-up", "roadmap"],
    ["Microgravity pharma synthesis", "space", "C*", "reaction", "yield", "roadmap"],
    ["Cryo propellant transfer", "space", "H₂", "heat", "reliability", "direct"],
    ["Inflatable habitats", "space", "C*", "fabrication", "reliability", "roadmap"],
    ["Optical inter-satellite links", "space", "Si", "deposition", "reliability", "direct"],
    ["Space elevators (tether cable)", "space", "C*", "fabrication", "supply", "analogue"],
    ["Helium-3 lunar mining", "space", "He", "separation", "yield", "analogue"],
  ];

  const ENTRIES = RAW.map(([name, sector, chemical, unitOp, bottleneck, evidence], i) => {
    const pid = `PFD-${String(100 + i + 1).padStart(3, "0")}`;
    const trl = Math.max(1, Math.min(9, 2 + ((i * 7) % 8)));
    const mrl = Math.max(1, Math.min(9, 1 + ((i * 5 + 3) % 8)));
    const irl = Math.max(1, Math.min(9, 1 + ((i * 3 + 5) % 7)));
    return {
      pid, name, sector, chemical, unitOp, bottleneck, evidence,
      trl, mrl, irl,
      scaleTrigger: scaleTriggerFor(bottleneck),
    };
  });

  function scaleTriggerFor(bn) {
    const map = {
      "energy-intensity": "low-cost utilities + waste heat",
      "separations":      "selective membranes at scale",
      "yield":            "tuned catalysts, recycle loops",
      "reliability":      "thousand-cycle qualification",
      "supply":           "secondary supply + substitutes",
      "infrastructure":   "shared utilities + standards",
      "cost":             "capex compression by 4×",
      "safety":           "containment + permitting paths",
      "scale-up":         "modular replicable reactor",
      "integration":      "fitting existing grids/plants",
      "regulation":       "approved performance class",
      "purity":           "in-line metrology + control",
    };
    return map[bn] || "manufacturable, repeatable, integrated";
  }

  // Compute sector counts
  for (const s of SECTORS) {
    s.count = ENTRIES.filter(e => e.sector === s.id).length;
  }

  // Featured case studies
  const FEATURED = [
    {
      pid: "PFD-117",
      name: "Atmospheric Water Harvesting",
      sector: "water",
      inputs: ["S-101  Ambient air", "Q-301  Heat input"],
      output: "P-401  Potable water",
      steps: [
        ["B-101", "Ambient air"],
        ["A-201", "Sorbent capture"],
        ["R-301", "Regeneration"],
        ["HX-401", "Condensation"],
        ["F-501", "Purification"],
        ["T-601", "Storage"],
      ],
      bottleneck: "Energy use at low humidity",
      trigger: "Low-cost sorbents + waste heat",
      readiness: "MRL · IRL",
    },
    {
      pid: "PFD-104",
      name: "Green Hydrogen Electrolysis",
      sector: "energy",
      inputs: ["S-101  Deionized water", "E-201  Renewable power"],
      output: "P-401  H₂  ·  O₂",
      steps: [
        ["B-101", "Water treatment"],
        ["E-201", "Electrolyzer stack"],
        ["S-301", "Gas separation"],
        ["C-401", "Compression"],
        ["F-501", "Drying"],
        ["T-601", "H₂ storage"],
      ],
      bottleneck: "Stack durability + iridium loading",
      trigger: "PGM-free catalysts at $/kW < 300",
      readiness: "MRL",
    },
    {
      pid: "PFD-039",
      name: "Solid-Sorbent Direct Air Capture",
      sector: "carbon",
      inputs: ["S-101  Ambient air", "Q-301  Waste heat"],
      output: "P-401  CO₂ (food / fuel / mineralization)",
      steps: [
        ["B-101", "Contactor inlet"],
        ["A-201", "Amine sorbent"],
        ["R-301", "Thermal swing"],
        ["S-401", "CO₂ desorption"],
        ["F-501", "Polishing"],
        ["T-601", "Compression"],
      ],
      bottleneck: "Energy + sorbent cycle life",
      trigger: "Sorbents lasting 10⁴ cycles",
      readiness: "MRL · cost",
    },
  ];

  /* ── Source bank ──────────────────────────────────────────
     Representative citations across sectors and postures.   */
  const SOURCES = [
    { id: "src-001", year: 2023, title: "Net Zero Roadmap: A Global Pathway",                  org: "IEA",                                    sector: "energy",        ev: "roadmap"  },
    { id: "src-002", year: 2024, title: "Annual Technology Baseline (ATB)",                    org: "NREL",                                   sector: "energy",        ev: "direct"   },
    { id: "src-003", year: 2024, title: "Hydrogen Shot Technology Assessment",                 org: "DOE",                                    sector: "energy",        ev: "roadmap"  },
    { id: "src-004", year: 2024, title: "Battery Storage Cost & Performance Update",           org: "Lazard",                                 sector: "energy",        ev: "direct"   },
    { id: "src-005", year: 2024, title: "Long Duration Energy Storage Council Report",         org: "LDES Council",                           sector: "energy",        ev: "roadmap"  },
    { id: "src-006", year: 2023, title: "NIF Ignition Achievement — Shot N221204",              org: "LLNL",                                   sector: "energy",        ev: "direct"   },
    { id: "src-007", year: 2024, title: "ITER Construction Status Update",                     org: "ITER Organization",                      sector: "energy",        ev: "roadmap"  },
    { id: "src-008", year: 2023, title: "Enhanced Geothermal Systems — Frontier Observatory",  org: "DOE / FORGE",                            sector: "energy",        ev: "direct"   },
    { id: "src-009", year: 2024, title: "Commonwealth Fusion Systems — SPARC Progress",        org: "CFS",                                    sector: "energy",        ev: "roadmap"  },
    { id: "src-010", year: 2024, title: "IPCC AR6 Working Group III · Mitigation",             org: "IPCC",                                   sector: "carbon",        ev: "direct"   },
    { id: "src-011", year: 2024, title: "Mammoth DAC Operations Bulletin",                     org: "Climeworks",                             sector: "carbon",        ev: "direct"   },
    { id: "src-012", year: 2023, title: "DAC Hubs Program — Phase 1 Awards",                   org: "DOE",                                    sector: "carbon",        ev: "roadmap"  },
    { id: "src-013", year: 2024, title: "Carbon to Value Initiative Annual Review",            org: "RMI",                                    sector: "carbon",        ev: "roadmap"  },
    { id: "src-014", year: 2023, title: "Ocean Alkalinity Enhancement — Field Trials",         org: "Ocean Visions",                          sector: "carbon",        ev: "analogue" },
    { id: "src-015", year: 2024, title: "Enhanced Rock Weathering Lifecycle Assessment",       org: "Nature Communications",                  sector: "carbon",        ev: "roadmap"  },
    { id: "src-016", year: 2024, title: "Mineralized Concrete — Field Performance Bulletin",   org: "CarbonCure / Solidia",                   sector: "carbon",        ev: "direct"   },
    { id: "src-017", year: 2024, title: "Aqueduct 4.0 Water Risk Atlas",                       org: "WRI",                                    sector: "water",         ev: "direct"   },
    { id: "src-018", year: 2023, title: "Atmospheric Water Generation Performance Survey",     org: "DOE / Water Power Tech.",                sector: "water",         ev: "direct"   },
    { id: "src-019", year: 2024, title: "Direct Lithium Extraction Pilot Data",                org: "Lilac Solutions",                        sector: "water",         ev: "roadmap"  },
    { id: "src-020", year: 2023, title: "Electrochemical PFAS Destruction — EPA Bench Tests",  org: "US EPA",                                 sector: "water",         ev: "direct"   },
    { id: "src-021", year: 2024, title: "Forward Osmosis Membrane Service Life Study",         org: "Aquaporin / J. Membr. Sci.",             sector: "water",         ev: "direct"   },
    { id: "src-022", year: 2024, title: "Critical Minerals Outlook",                           org: "USGS",                                   sector: "materials",     ev: "direct"   },
    { id: "src-023", year: 2023, title: "Perovskite Tandem Stability — 25-Year Outdoor Data",  org: "Oxford PV / NREL",                       sector: "materials",     ev: "direct"   },
    { id: "src-024", year: 2024, title: "MOF Sorbent Cycle-Life Benchmarks",                   org: "Nature Materials",                       sector: "materials",     ev: "roadmap"  },
    { id: "src-025", year: 2024, title: "Solid-Electrolyte Conductivity Roadmap",              org: "BMW / Solid Power",                      sector: "materials",     ev: "roadmap"  },
    { id: "src-026", year: 2023, title: "Graphene Industrialization Survey",                   org: "Graphene Council",                       sector: "materials",     ev: "analogue" },
    { id: "src-027", year: 2024, title: "Roll-to-Roll Manufacturing Yield Reports",            org: "Fraunhofer ISE",                         sector: "manufacturing", ev: "direct"   },
    { id: "src-028", year: 2024, title: "Modular Nuclear Factory Cost Models",                 org: "IEEFA / MIT",                            sector: "manufacturing", ev: "roadmap"  },
    { id: "src-029", year: 2023, title: "Cultivated Meat Techno-Economic Analysis",            org: "Good Food Institute",                    sector: "manufacturing", ev: "roadmap"  },
    { id: "src-030", year: 2024, title: "Precision Fermentation Capacity Map",                 org: "Synonym",                                sector: "manufacturing", ev: "direct"   },
    { id: "src-031", year: 2024, title: "Closed-Loop Battery Recycling — Recovery Yields",     org: "Redwood Materials",                      sector: "manufacturing", ev: "direct"   },
    { id: "src-032", year: 2024, title: "FOAK Project Finance — Spec Sheet",                   org: "Breakthrough Energy",                    sector: "manufacturing", ev: "roadmap"  },
    { id: "src-033", year: 2024, title: "UAM Concept of Operations 2.0",                       org: "FAA",                                    sector: "cities",        ev: "roadmap"  },
    { id: "src-034", year: 2024, title: "Joby S4 Type Certification Status",                   org: "Joby Aviation",                          sector: "cities",        ev: "direct"   },
    { id: "src-035", year: 2024, title: "Heat Pump Retrofit Cost Curves",                      org: "RMI / BloombergNEF",                     sector: "cities",        ev: "direct"   },
    { id: "src-036", year: 2023, title: "Vertical Farm Energy Benchmark",                      org: "Cornell CEA",                            sector: "cities",        ev: "direct"   },
    { id: "src-037", year: 2024, title: "District Geothermal — Eversource Pilot",              org: "Eversource",                             sector: "cities",        ev: "direct"   },
    { id: "src-038", year: 2024, title: "Smart Glass Switching-Cycle Life Report",             org: "View / Sage",                            sector: "cities",        ev: "direct"   },
    { id: "src-039", year: 2024, title: "Starship Flight Test Bulletin · IFT-5",               org: "SpaceX",                                 sector: "space",         ev: "direct"   },
    { id: "src-040", year: 2024, title: "Artemis Reference Architecture Update",               org: "NASA",                                   sector: "space",         ev: "roadmap"  },
    { id: "src-041", year: 2023, title: "Lunar Surface ISRU Capabilities Roadmap",             org: "NASA Tech. Memorandum",                  sector: "space",         ev: "roadmap"  },
    { id: "src-042", year: 2024, title: "On-Orbit Manufacturing Pilot — ISS NL",               org: "ISS National Lab",                       sector: "space",         ev: "direct"   },
    { id: "src-043", year: 2023, title: "Asteroid Mining — Resource Modeling",                 org: "Colorado School of Mines",               sector: "space",         ev: "analogue" },
    { id: "src-044", year: 2024, title: "Space Debris Active Removal Status",                  org: "ESA Space Safety",                       sector: "space",         ev: "roadmap"  },
    { id: "src-045", year: 2024, title: "Electricity Outlook · 2026 Edition",                  org: "BloombergNEF",                           sector: "energy",        ev: "direct"   },
    { id: "src-046", year: 2024, title: "Manufacturing Readiness Level Deskbook v3.0",         org: "OUSD R&E (Manufacturing)",               sector: "manufacturing", ev: "direct"   },
    { id: "src-047", year: 2023, title: "Advanced Air Mobility Implementation Plan: Innovate28", org: "FAA", sector: "cities", ev: "roadmap" },
    { id: "src-048", year: 2025, title: "Advanced Air Mobility National Strategy", org: "US DOT", sector: "cities", ev: "roadmap" },
    { id: "src-049", year: 2024, title: "Advanced Air Mobility: Opportunities, Challenges, and Research Needs", org: "NTL", sector: "cities", ev: "direct" },
    { id: "src-050", year: 2026, title: "Advanced Air Mobility Mission", org: "NASA", sector: "cities", ev: "direct" },
    { id: "src-051", year: 2020, title: "Advancing Aerial Mobility: A National Blueprint, chapter 2", org: "NASEM", sector: "cities", ev: "analogue" },
    { id: "src-052", year: 2024, title: "Graphene oxide-based membranes for water desalination: progress and challenges", org: "npj Clean Water", sector: "materials", ev: "roadmap" },
    { id: "src-053", year: 2015, title: "Graphene-based membranes", org: "Chemical Society Reviews", sector: "materials", ev: "direct" },
    { id: "src-054", year: 2018, title: "Building the space elevator: lessons from biological design", org: "Journal of the Royal Society Interface", sector: "materials", ev: "analogue" },
    { id: "src-055", year: 2020, title: "Self-healing polymers", org: "Nature Reviews Materials", sector: "materials", ev: "direct" },
    { id: "src-056", year: 2024, title: "Radiative cooling and indoor light management enabled by a transparent, haze-free metafilm", org: "Nature Communications", sector: "materials", ev: "direct" },
    { id: "src-057", year: 2024, title: "A state-of-the-art review of novel aerogel insulation materials for building applications", org: "Energy Sources, Part A", sector: "materials", ev: "roadmap" },
    { id: "src-058", year: 2022, title: "Icephobic/anti-icing properties of superhydrophobic surfaces", org: "Advances in Colloid and Interface Science", sector: "materials", ev: "roadmap" },
    { id: "src-059", year: 2024, title: "Scalable robust photothermal superhydrophobic coatings", org: "Nature Communications", sector: "materials", ev: "direct" },
    { id: "src-060", year: 2024, title: "Breaking the limits of acoustic science: A review of acoustic metamaterials", org: "Materials Science and Engineering: R", sector: "materials", ev: "roadmap" },
    { id: "src-061", year: 2023, title: "An overview of atmospheric water harvesting methods", org: "PMC / peer-reviewed review", sector: "water", ev: "roadmap" },
    { id: "src-062", year: 2020, title: "MOF water harvesters", org: "Nature Nanotechnology review context", sector: "water", ev: "direct" },
    { id: "src-063", year: 2018, title: "Adsorption-based atmospheric water harvesting device for arid climates", org: "Nature Communications", sector: "water", ev: "analogue" },
    { id: "src-064", year: 2021, title: "Adsorption-based atmospheric water harvesting", org: "Joule", sector: "water", ev: "direct" },
    { id: "src-065", year: 2024, title: "Advancements in atmospheric water harvesting", org: "Communications Engineering", sector: "water", ev: "direct" },
    { id: "src-066", year: 2023, title: "Global water yield strategy for metal-organic-framework-based atmospheric water harvesting", org: "Cell Reports Physical Science", sector: "water", ev: "direct" },
    { id: "src-067", year: 2023, title: "The U.S. Biomanufacturing Economy: Value Added, Supply Chains, Cost, Sustainability, and Efficiency", org: "NIST AMS 100-52", sector: "manufacturing", ev: "direct" },
    { id: "src-068", year: 2023, title: "Successes and Challenges in Biomanufacturing", org: "NASEM", sector: "manufacturing", ev: "roadmap" },
    { id: "src-069", year: null, title: "Vaccines on Demand Program", org: "BARDA", sector: "manufacturing", ev: "roadmap" },
    { id: "src-070", year: 2023, title: "Food Safety Aspects of Cell-Based Food", org: "FAO and WHO", sector: "manufacturing", ev: "roadmap" },
    { id: "src-071", year: 2022, title: "Sensor technologies for quality control in engineered tissue manufacturing", org: "PMC", sector: "manufacturing", ev: "direct" },
    { id: "src-072", year: 2021, title: "Quality control methods in musculoskeletal tissue engineering", org: "Bone Research", sector: "manufacturing", ev: "direct" },
    { id: "src-073", year: 2024, title: "Carbon Capture, Utilisation and Storage", org: "IEA", sector: "carbon", ev: "direct" },
    { id: "src-074", year: 2020, title: "CCUS in Clean Energy Transitions", org: "IEA", sector: "carbon", ev: "roadmap" },
    { id: "src-075", year: 2024, title: "Direct Air Capture", org: "IEA", sector: "carbon", ev: "roadmap" },
    { id: "src-076", year: 2019, title: "Negative Emissions Technologies and Reliable Sequestration: Direct Air Capture chapter", org: "NASEM", sector: "carbon", ev: "direct" },
    { id: "src-077", year: 2024, title: "Cement", org: "IEA", sector: "carbon", ev: "roadmap" },
    { id: "src-078", year: 2018, title: "Technology Roadmap: Low-Carbon Transition in the Cement Industry", org: "IEA and Cement Sustaina", sector: "carbon", ev: "roadmap" },
    { id: "src-079", year: 2024, title: "Global decarbonization potential of CO2 mineralization in concrete materials", org: "Nature Communications / PMC", sector: "carbon", ev: "direct" },
    { id: "src-080", year: 2024, title: "Global Hydrogen Review 2024", org: "IEA", sector: "materials", ev: "roadmap" },
    { id: "src-081", year: 2025, title: "Global Hydrogen Review 2025", org: "IEA", sector: "materials", ev: "direct" },
    { id: "src-082", year: 2021, title: "Ammonia Technology Roadmap: Towards more sustainable nitrogen fertiliser production", org: "IEA", sector: "materials", ev: "roadmap" },
    { id: "src-083", year: 2025, title: "Global Critical Minerals Outlook 2025", org: "IEA", sector: "materials", ev: "direct" },
    { id: "src-084", year: 2025, title: "Mineral Commodity Summaries 2025", org: "USGS", sector: "materials", ev: "direct" },
    { id: "src-085", year: 2026, title: "DOE Explains.", org: "DOE Office of Science", sector: "energy", ev: "roadmap" },
    { id: "src-086", year: 2023, title: "Artificial Photosynthesis: Current Advancements and Future Prospects", org: "Catalysts / PMC", sector: "energy", ev: "roadmap" },
    { id: "src-087", year: 2008, title: "Whole Brain Emulation: A Roadmap", org: "Future of Humanity Institute, University of Oxford", sector: "manufacturing", ev: "analogue" },
    { id: "src-088", year: 2022, title: "The Prospects of Whole Brain Emulation within the Next Half-Century", org: "PhilArchive copy", sector: "manufacturing", ev: "direct" },
    { id: "src-089", year: 2025, title: "How “Real” is Your Real-Time Simultaneous Speech-to-Text Translation? Transactions of the Association for Computational Linguistics", org: "Papi, S., et al", sector: "manufacturing", ev: "direct" },
    { id: "src-090", year: 2024, title: "Recent Advances in End-to-End Simultaneous Speech Translation", org: "IJCAI", sector: "manufacturing", ev: "roadmap" },
    { id: "src-091", year: 2025, title: "Real-time speech-to-speech translation", org: "Google Research", sector: "manufacturing", ev: "analogue" },
    { id: "src-092", year: 2019, title: "Quantum Computing: Progress and Prospects", org: "NASEM", sector: "materials", ev: "direct" },
    { id: "src-093", year: 2025, title: "Quantum Computing Explained", org: "NIST", sector: "materials", ev: "direct" },
    { id: "src-094", year: 2023, title: "Data Centres and Data Transmission Networks", org: "IEA", sector: "materials", ev: "direct" },
    { id: "src-095", year: 2025, title: "Energy demand from AI", org: "IEA", sector: "materials", ev: "direct" },
    { id: "src-096", year: null, title: "Personal Fabrication Research in HCI and Graphics. MIT CSAIL / HCI Engineering Group", org: "Baudisch, P., and Mueller, S", sector: "manufacturing", ev: "roadmap" },
    { id: "src-097", year: 2023, title: "Advancing Plastic Recycling: Challenges and Opportunities in Distributed Recycling by Additive Manufacturing", org: "Polymers", sector: "manufacturing", ev: "roadmap" },
    { id: "src-098", year: 2020, title: "Plastic recycling in additive manufacturing: A systematic literature review and opportunities for the circular economy", org: "Journal of Cleaner Production", sector: "manufacturing", ev: "roadmap" },
    { id: "src-099", year: 2025, title: "ACM Computing Surveys", org: "A Review on Human–Robot Trust in Home Service R", sector: "cities", ev: "roadmap" },
    { id: "src-100", year: 2019, title: "Journal of Information, Communication and Ethics in Society", org: "Responsible domestic robotics: exploring ethica", sector: "cities", ev: "direct" },
    { id: "src-101", year: 2023, title: "Transportation Research Part D", org: "Drones in last-mile delivery: A systematic revi", sector: "cities", ev: "roadmap" },
    { id: "src-102", year: null, title: "Package Delivery by Drone, Part 135", org: "FAA", sector: "cities", ev: "direct" },
    { id: "src-103", year: 2023, title: "Smart Adaptive Homes and Their Potential to Improve Space Efficiency and Personalisation", org: "Buildings", sector: "cities", ev: "direct" },
    { id: "src-104", year: null, title: "TRANSFORM: Dynamic and Adaptive Furniture", org: "MIT Media Lab / Tangible Media Group", sector: "cities", ev: "analogue" },
    { id: "src-105", year: 2021, title: "Techno-Economic Analysis of Lithium Extraction from Geothermal Brines", org: "National Renewable Energy Laboratory", sector: "materials", ev: "direct" },
    { id: "src-106", year: 2024, title: "Digital Twins for Advanced Manufacturing", org: "NIST", sector: "manufacturing", ev: "direct" },
    { id: "src-107", year: 2023, title: "Foundational Research Gaps and Future Directions for Digital Twins", org: "NASEM", sector: "manufacturing", ev: "direct" },
    { id: "src-108", year: 2021, title: "Design and manufacture of AR head-mounted displays: A review", org: "Light: Advanced Manufacturing", sector: "cities", ev: "roadmap" },
    { id: "src-109", year: 2023, title: "Waveguide-based augmented reality displays", org: "Light: Science & Applications", sector: "cities", ev: "roadmap" },
    { id: "src-110", year: 2024, title: "Haptic Sensing and Feedback Techniques toward Virtual Reality", org: "Advanced Science / PMC", sector: "cities", ev: "roadmap" },
    { id: "src-111", year: 2020, title: "Toward the next-generation VR/AR optics: A review of holographic near-eye displays from a human-centric perspective", org: "Optica", sector: "cities", ev: "roadmap" },
    { id: "src-112", year: 2022, title: "Holographic techniques for augmented reality and virtual reality near-eye displays", org: "Light: Advanced Manufacturing", sector: "cities", ev: "roadmap" },
    { id: "src-113", year: 2020, title: "Transparent OLED: 8 Things You Need to Know About Transparent OLED Technology", org: "Planar", sector: "cities", ev: "analogue" },
    { id: "src-114", year: 2025, title: "Transparent OLEDs: Introduction and Market Status", org: "OLED-Info", sector: "cities", ev: "analogue" },
    { id: "src-115", year: 2023, title: "NASA's Electrified Aircraft Propulsion Research and Development Efforts", org: "NASA Office of Inspector General", sector: "cities", ev: "direct" },
    { id: "src-116", year: 2026, title: "Electrified Aircraft Propulsion", org: "NASA", sector: "cities", ev: "direct" },
    { id: "src-117", year: 2023, title: "Pathways to Commercial Liftoff: Long Duration Energy Storage", org: "DOE", sector: "energy", ev: "direct" },
    { id: "src-118", year: 2024, title: "Achieving the Promise of Low-Cost Long Duration Energy Storage", org: "DOE", sector: "energy", ev: "roadmap" },
    { id: "src-119", year: 2019, title: "A Strategic Plan for U.S", org: "Burning Plasma Research", sector: "energy", ev: "direct" },
    { id: "src-120", year: 2020, title: "Powering the Future: Fusion & Plasmas", org: "FESAC", sector: "energy", ev: "roadmap" },
    { id: "src-121", year: 2025, title: "Fusion Energy: Additional Planning Would Strengthen DOE's Efforts to Advance Commercialization", org: "US GAO", sector: "energy", ev: "roadmap" },
    { id: "src-122", year: 2024, title: "Fusion Blankets Research Objectives", org: "EPRI / U.S. Department of Energy", sector: "energy", ev: "direct" },
    { id: "src-123", year: 2025, title: "A state-of-the-art review of underground logistics systems", org: "Tunnelling and Underground Space Technology", sector: "cities", ev: "analogue" },
    { id: "src-124", year: 2015, title: "Underground Systems in Service of City Logistics", org: "LOGIC", sector: "cities", ev: "direct" },
    { id: "src-125", year: 2026, title: "Smart Urban Logistics and Tube-Based Freight Systems", org: "Smart Cities 9(3), 52", sector: "cities", ev: "direct" },
    { id: "src-126", year: null, title: "Off-Site and Modular Construction Explained", org: "National Institute of Building Sciences / WBDG", sector: "cities", ev: "direct" },
    { id: "src-127", year: null, title: "Modular and Off-Site Construction Guide", org: "American Institute of Architects and National I", sector: "cities", ev: "direct" },
    { id: "src-128", year: 2025, title: "Modular Construction: A Comprehensive Review", org: "Buildings 15(12), 2020", sector: "cities", ev: "roadmap" },
    { id: "src-129", year: 2023, title: "Investigation of the Severity of Modular Construction Barriers", org: "Journal of Construction Engineering and Managem", sector: "cities", ev: "direct" },
    { id: "src-130", year: 2025, title: "Cool Walkability Planning: Providing Pedestrian Thermal Comfort in Hot Climate Cities", org: "Victoria Transport Policy Institute", sector: "cities", ev: "direct" },
    { id: "src-131", year: 2024, title: "Assessing Cool Corridor Heat Resilience Strategies for Human-Scale Transportation", org: "Iroz-Elardo, N., et al", sector: "cities", ev: "direct" },
    { id: "src-132", year: 2020, title: "City design for health and resilience in hot and dry climates", org: "BMJ / PMC", sector: "cities", ev: "direct" },
    { id: "src-133", year: 2022, title: "Behavioural thermal regulation explains pedestrian path choice in a hot urban environment", org: "Scientific Reports", sector: "cities", ev: "direct" },
    { id: "src-134", year: 2023, title: "Pneumatic Urban Waste Collection Systems: A Review", org: "Applied Sciences 13(2), 877", sector: "cities", ev: "roadmap" },
    { id: "src-135", year: 2014, title: "Assessing the financial and environmental performance of underground automated vacuum waste collection systems", org: "Tunnelling and Underground Space Technology", sector: "cities", ev: "direct" },
    { id: "src-136", year: null, title: "Environmental Protection Agency. Sustainable Materials Management", org: "U.S", sector: "cities", ev: "direct" },
    { id: "src-137", year: 2008, title: "Desalination: A National Perspective", org: "NRC", sector: "water", ev: "direct" },
    { id: "src-138", year: 2019, title: "Desalination", org: "USGS", sector: "water", ev: "direct" },
    { id: "src-139", year: 2026, title: "Desalination Basics", org: "DOE", sector: "water", ev: "direct" },
    { id: "src-140", year: 2024, title: "Interim Guidance on the Destruction and Disposal of PFAS and Materials Containing PFAS", org: "US EPA", sector: "water", ev: "direct" },
    { id: "src-141", year: 2026, title: "Water Reuse and Recycling / National Water Reuse Action Plan", org: "US EPA", sector: "water", ev: "roadmap" },
    { id: "src-142", year: 2012, title: "Water Reuse: Potential for Expanding the Nation's Water Supply Through Reuse of Municipal Wastewater", org: "NRC", sector: "water", ev: "direct" },
    { id: "src-143", year: 2022, title: "Industrial Decarbonization Roadmap", org: "DOE", sector: "carbon", ev: "roadmap" },
    { id: "src-144", year: 2020, title: "Iron and Steel Technology Roadmap", org: "IEA", sector: "carbon", ev: "roadmap" },
    { id: "src-145", year: 2023, title: "CHIPS Metrology Program", org: "NIST", sector: "manufacturing", ev: "roadmap" },
    { id: "src-146", year: 2023, title: "Metrology Gaps in the Semiconductor Ecosystem", org: "NIST", sector: "manufacturing", ev: "direct" },
    { id: "src-147", year: 2015, title: "Yield Enhancement", org: "International Technology Roadmap for Semiconduc", sector: "manufacturing", ev: "roadmap" },
    { id: "src-148", year: 2024, title: "Lights-out factories: review and prospect", org: "Journal publication indexed by Beijing Institut", sector: "manufacturing", ev: "direct" },
    { id: "src-149", year: 2024, title: "A focused review on techniques for achieving cloaking using metamaterials", org: "Optik", sector: "materials", ev: "roadmap" },
    { id: "src-150", year: 2021, title: "From invisibility to intelligent antennas: A review of electromagnetic cloaking", org: "EPJ Applied Metamaterials", sector: "materials", ev: "roadmap" },
    { id: "src-151", year: null, title: "C., et al. Claytronics: A Scalable Basis for Future Robots. Carnegie Mellon University", org: "Goldstein, S", sector: "materials", ev: "analogue" },
    { id: "src-152", year: 2022, title: "Shape morphing mechanical metamaterials through reversible plasticity", org: "Science Robotics", sector: "materials", ev: "direct" },
    { id: "src-153", year: 2022, title: "APL Materials", org: "Programmable shape-morphing of rose-shaped mech", sector: "materials", ev: "direct" },
    { id: "src-154", year: 2022, title: "A methodological review on self-healing asphalt pavements", org: "Construction and Building Materials", sector: "cities", ev: "roadmap" },
    { id: "src-155", year: 2021, title: "Self-Healing Asphalt: A Systematic Bibliometric Analysis", org: "Materials", sector: "cities", ev: "roadmap" },
    { id: "src-156", year: 2024, title: "The self-healing performance of asphalt binder and mixtures", org: "Innovative Infrastructure Solutions", sector: "cities", ev: "roadmap" },
    { id: "src-157", year: 2024, title: "A comprehensive review on self-cleaning glass surfaces", org: "Materials", sector: "materials", ev: "roadmap" },
    { id: "src-158", year: 2025, title: "A comprehensive review on realization of self-cleaning surfaces", org: "Discover Materials", sector: "materials", ev: "roadmap" },
    { id: "src-159", year: 2023, title: "Superior self-cleaning surfaces via the synergy of superhydrophobicity and photocatalysis", org: "Journal of Cleaner Production", sector: "materials", ev: "direct" },
    { id: "src-160", year: 2024, title: "Clathrate metal superhydrides under high-pressure conditions", org: "National Science Review", sector: "materials", ev: "roadmap" },
    { id: "src-161", year: 2024, title: "Are hydrides under high-pressure–high-temperature superconductors? National Science Review", org: "Hirsch, J. E", sector: "materials", ev: "direct" },
    { id: "src-162", year: 2022, title: "Room-temperature superconductivity study retracted", org: "Science", sector: "materials", ev: "analogue" },
    { id: "src-163", year: 2025, title: "Journal of Applied Physics", org: "Roadblocks to ambient-pressure room-temperature", sector: "materials", ev: "direct" },
    { id: "src-164", year: 2020, title: "Senolytic drugs: from discovery to translation", org: "Journal of Internal Medicine", sector: "manufacturing", ev: "roadmap" },
    { id: "src-165", year: 2024, title: "Senolytics: from pharmacological inhibitors to immunotherapies, a promising future? npj Aging", org: "Lelarge, V., et al", sector: "manufacturing", ev: "roadmap" },
    { id: "src-166", year: null, title: "NCT04313634. Targeting Cellular Senescence With Senolytics to Improve Skeletal Health in Older Humans", org: "ClinicalTrials.gov", sector: "manufacturing", ev: "direct" },
    { id: "src-167", year: 2024, title: "Evaluating the Safety and Efficacy of Hemoglobin-Based Blood Substitutes", org: "US FDA", sector: "manufacturing", ev: "direct" },
    { id: "src-168", year: 2023, title: "Hemoglobin-Based Oxygen Carriers: Where Are We Now in 2023? International Journal of Molecular Sciences", org: "Chen, L., et al", sector: "manufacturing", ev: "roadmap" },
    { id: "src-169", year: 2018, title: "Current Trends and Challenges in the Clinical Translation of Nanoparticulate Nanomedicines", org: "Frontiers in Pharmacology", sector: "manufacturing", ev: "roadmap" },
    { id: "src-170", year: 2025, title: "Nano bio-robots: a new frontier in targeted therapeutic delivery", org: "Frontiers / PMC", sector: "manufacturing", ev: "analogue" },
    { id: "src-171", year: 2021, title: "Implanted Brain-Computer Interface Devices for Patients with Paralysis or Amputation: Non-clinical Testing and Clinical Considerations", org: "US FDA", sector: "manufacturing", ev: "direct" },
    { id: "src-172", year: 2025, title: "Science & Tech Spotlight: Brain-Computer Interfaces", org: "US GAO", sector: "manufacturing", ev: "roadmap" },
    { id: "src-173", year: 2020, title: "A Review of Sensory Feedback in Upper-Limb Prostheses From the Perspective of Human Motor Control", org: "Frontiers in Neuroscience", sector: "manufacturing", ev: "roadmap" },
    { id: "src-174", year: 2022, title: "Multichannel haptic feedback unlocks prosthetic hand dexterity", org: "Scientific Reports", sector: "manufacturing", ev: "direct" },
    { id: "src-175", year: 2018, title: "Reflecting health: smart mirrors for personalized medicine", org: "npj Digital Medicine", sector: "cities", ev: "analogue" },
    { id: "src-176", year: 2024, title: "Internet-of-Mirrors for connected healthcare and beauty", org: "Internet of Things and Cyber-Physical Systems", sector: "cities", ev: "direct" },
    { id: "src-177", year: 2022, title: "New Directions for Chemical Engineering", org: "NASEM", sector: "manufacturing", ev: "analogue" },
    { id: "src-178", year: 2020, title: "Deployment of Deep Decarbonization Technologies", org: "NASEM", sector: "manufacturing", ev: "direct" },
    { id: "src-179", year: null, title: "Rapid Advancement in Process Intensification Deployment", org: "RAPID Manufacturing Institute / AIChE", sector: "manufacturing", ev: "roadmap" },
    { id: "src-180", year: 2024, title: "Individual wearable air purifier protects against pollen, house dust mite, and cat allergens", org: "Allergy, Asthma & Clinical Immunology", sector: "cities", ev: "direct" },
    { id: "src-181", year: 2025, title: "Air Purifier Buying Guide", org: "Consumer Reports", sector: "cities", ev: "analogue" },
    { id: "src-182", year: 2022, title: "Personal Cooling Garments: A Review", org: "Polymers", sector: "cities", ev: "roadmap" },
    { id: "src-183", year: 2025, title: "Enhancing thermal comfort: a comprehensive review of wearable cooling systems", org: "Next Energy", sector: "cities", ev: "roadmap" },
    { id: "src-184", year: 2026, title: "Emerging Technology Program", org: "US FDA", sector: "manufacturing", ev: "direct" },
    { id: "src-185", year: 2025, title: "Advanced Manufacturing Technologies Designation Program Guidance", org: "US FDA", sector: "manufacturing", ev: "direct" },
    { id: "src-186", year: 2025, title: "Examples of Accepted Emerging Technologies", org: "US FDA", sector: "manufacturing", ev: "roadmap" },
    { id: "src-187", year: 2024, title: "Present and future of micro-transfer printing for heterogeneous integration", org: "APL Photonics", sector: "manufacturing", ev: "direct" },
    { id: "src-188", year: 2017, title: "Transfer print techniques for heterogeneous integration of photonic components", org: "Progress in Quantum Electronics", sector: "manufacturing", ev: "direct" },
    { id: "src-189", year: 2024, title: "Polymer Advanced Technologies", org: "Recent advances in conductive materials for pri", sector: "manufacturing", ev: "roadmap" },
    { id: "src-190", year: 2023, title: "Technology Readiness Levels", org: "NASA", sector: "manufacturing", ev: "direct" },
    { id: "src-191", year: 2020, title: "Technology Readiness Assessment Guide, GAO-20-48G", org: "US GAO", sector: "manufacturing", ev: "direct" },
    { id: "src-192", year: 2016, title: "Manufacturing Readiness Level Deskbook, version 2.5", org: "US Department of Defense", sector: "manufacturing", ev: "direct" },
    { id: "src-193", year: 2010, title: "Contextual Role of TRLs and MRLs in Technology Management", org: "Sandia National Laboratories / OSTI", sector: "manufacturing", ev: "direct" },
    { id: "src-194", year: 2009, title: "Defining an Integration Readiness Level for Defense Acquisition", org: "INCOSE / Systems Engineering context", sector: "manufacturing", ev: "direct" },
    { id: "src-195", year: 2020, title: "On-site autonomous construction robots: Toward unsupervised building", org: "Automation in Construction", sector: "cities", ev: "roadmap" },
    { id: "src-196", year: 2023, title: "Construction Robotics: From Automation to Collaboration", org: "Annual Review of Control, Robotics, and Autonom", sector: "cities", ev: "roadmap" },
    { id: "src-197", year: 2024, title: "Transforming Construction: Automation and Robotics for a Safer Future", org: "NIOSH", sector: "cities", ev: "direct" },
    { id: "src-198", year: 2023, title: "Insights into evaluating and using industrial exoskeletons", org: "International Journal of Industrial Ergonomics", sector: "manufacturing", ev: "roadmap" },
    { id: "src-199", year: 2025, title: "Safety in Wearable Robotic Exoskeletons: Design, Control, and Regulatory Considerations", org: "ASME Journal of Mechanisms and Robotics", sector: "manufacturing", ev: "roadmap" },
    { id: "src-200", year: 2023, title: "The Ethics of Mandatory Exoskeleton Use in Commercial and Industrial Settings", org: "IEEE Transactions on Technology and Society", sector: "manufacturing", ev: "direct" },
    { id: "src-201", year: 2021, title: "Swarm Robotics: Past, Present, and Future", org: "Proceedings of the IEEE", sector: "cities", ev: "roadmap" },
    { id: "src-202", year: 2023, title: "A Review of Swarm Robotics in a Nutshell", org: "Drones 7(4), 269", sector: "cities", ev: "roadmap" },
    { id: "src-203", year: 2021, title: "Swarm Robotics: A Perspective on the Latest Reviewed Concepts and Applications", org: "Sensors", sector: "cities", ev: "roadmap" },
    { id: "src-204", year: 2023, title: "Better Windows, Better Outcomes: How Electrochromics Improve Health, Productivity, and Efficiency", org: "DOE Building Technologies O", sector: "cities", ev: "direct" },
    { id: "src-205", year: 2024, title: "Smart Manufacturing", org: "NIST", sector: "manufacturing", ev: "roadmap" },
    { id: "src-206", year: 2024, title: "Options for a National Plan for Smart Manufacturing", org: "NASEM", sector: "manufacturing", ev: "direct" },
    { id: "src-207", year: 2020, title: "Connecting, Deploying, and Using the Smart Manufacturing Systems Test Bed", org: "NIST", sector: "manufacturing", ev: "direct" },
    { id: "src-208", year: 2022, title: "National Strategy for Advanced Manufacturing", org: "White House / National Science and Technology C", sector: "manufacturing", ev: "roadmap" },
    { id: "src-209", year: 2023, title: "In-Situ Resource Utilization overview", org: "NASA", sector: "space", ev: "roadmap" },
    { id: "src-210", year: 2025, title: "Environmental Control and Life Support Systems (ECLSS)", org: "NASA", sector: "space", ev: "direct" },
    { id: "src-211", year: 2012, title: "Mars In Situ Resource Utilization Technology Evaluation", org: "NASA NTRS", sector: "space", ev: "direct" },
    { id: "src-212", year: null, title: "Life support and MELiSSA regenerative loop program", org: "ESA", sector: "space", ev: "direct" },
    { id: "src-213", year: 1997, title: "Advanced Technology for Human Support in Space", org: "NRC", sector: "space", ev: "direct" },
    { id: "src-214", year: 2024, title: "Space-Based Solar Power", org: "NASA Office of Technology, Policy, and Strategy", sector: "space", ev: "direct" },
    { id: "src-215", year: 2024, title: "New Study Updates NASA on Space-Based Solar Power", org: "NASA", sector: "space", ev: "direct" },
    { id: "src-216", year: 2024, title: "ESA accelerates the race towards clean energy from space", org: "ESA", sector: "space", ev: "roadmap" },
    { id: "src-217", year: 2024, title: "Atomically Precise Manufacturing of Silicon Electronics", org: "ACS / PMC", sector: "manufacturing", ev: "roadmap" },
    { id: "src-218", year: 2018, title: "Evaluating future nanotechnology: The net societal impacts of atomically precise manufacturing", org: "Futures", sector: "manufacturing", ev: "analogue" },
    { id: "src-219", year: 2020, title: "A molecular assembler that produces polymers", org: "Nature Communications", sector: "manufacturing", ev: "direct" },
    { id: "src-220", year: 1982, title: "Advanced Automation for Space Missions", org: "NASA Conference Publication 2255", sector: "manufacturing", ev: "direct" },
    { id: "src-221", year: 2016, title: "Are Self-Replicating Machines Feasible?", org: "Ellery, A", sector: "manufacturing", ev: "analogue" },
    { id: "src-222", year: 2022, title: "Self-replicating hierarchical modular robotic swarms", org: "Communications Engineering", sector: "manufacturing", ev: "direct" },
    { id: "src-223", year: 2024, title: "Sustainable Aviation Fuel State-of-Industry Report", org: "NREL", sector: "energy", ev: "direct" },
    { id: "src-224", year: null, title: "Department of Energy Alternative Fuels Data Center. Sustainable Aviation Fuel", org: "U.S", sector: "energy", ev: "direct" },
    { id: "src-225", year: 2024, title: "Forging a sustainable sky: aviation e-fuels review", org: "PMC / peer-reviewed review", sector: "energy", ev: "direct" },
    { id: "src-226", year: 2019, title: "Organs-On-Chips for Radiation Countermeasures", org: "US FDA", sector: "manufacturing", ev: "direct" },
    { id: "src-227", year: 2006, title: "Challenges in tissue engineering", org: "Journal of the Royal Society Interface", sector: "manufacturing", ev: "direct" },
    { id: "src-228", year: 2020, title: "Organ-on-a-Chip: A new paradigm for drug development", org: "Trends in Pharmacological Sciences / PMC", sector: "manufacturing", ev: "roadmap" },
    { id: "src-229", year: 2025, title: "Strategic Transit Automation Research Plan 2.0: 2023–2028", org: "FTA", sector: "cities", ev: "roadmap" },
    { id: "src-230", year: 2020, title: "Autonomous Shuttle Bus for Public Transportation: A Review", org: "Energies 13(11), 2917", sector: "cities", ev: "roadmap" },
    { id: "src-231", year: 2018, title: "Low-Speed Automated Shuttles: State of the Practice. U.S", org: "DOT / Volpe", sector: "cities", ev: "direct" },
    { id: "src-232", year: 2016, title: "Hyperloop Commercial Feasibility Analysis. U.S", org: "Department of Transportation / Volpe National T", sector: "cities", ev: "direct" },
    { id: "src-233", year: 2020, title: "Hyperloop Feasibility Study", org: "Mid-Ohio Regional Planning Commission", sector: "cities", ev: "direct" },
    { id: "src-234", year: 2005, title: "Report to Congress: Costs and Benefits of Magnetic Levitation", org: "FRA", sector: "cities", ev: "direct" },
    { id: "src-235", year: 2024, title: "Development and Challenges of Maglev Transportation", org: "IntechOpen", sector: "cities", ev: "roadmap" },
    { id: "src-236", year: 2021, title: "Impacts of Automated Vehicles on Highway Infrastructure", org: "FHWA", sector: "cities", ev: "direct" },
    { id: "src-237", year: 2024, title: "Connected and Autonomous Vehicle Technology: Determining the Impact on State DOT Maintenance Programs", org: "NCHRP Research Report 1084", sector: "cities", ev: "direct" },
    { id: "src-238", year: 2020, title: "Smart Roads: An Overview of What Future Mobility Will Look Like", org: "Infrastructures", sector: "cities", ev: "analogue" },
    { id: "src-239", year: 2016, title: "Seven chemical separations to change the world. Nature 532, 435–437", org: "DOI: 10.1038/532435a", sector: "manufacturing", ev: "direct" },
    { id: "src-240", year: 2015, title: "Bandwidth Study on Energy Use and Potential Energy Saving Opportunities in U.S", org: "DOE", sector: "manufacturing", ev: "analogue" },
    { id: "src-241", year: 2024, title: "Trends, Insights, and Future Prospects for Production in Controlled Environment Agriculture and Agrivoltaics", org: "USDA ERS", sector: "cities", ev: "direct" },
    { id: "src-242", year: 2021, title: "Review of energy efficiency in controlled environment agriculture", org: "Renewable and Sustainable Energy Reviews", sector: "cities", ev: "direct" },
    { id: "src-243", year: 2025, title: "The emergence of indoor agriculture as a driver of global energy demand", org: "Nature Food", sector: "cities", ev: "direct" },
    { id: "src-244", year: 2025, title: "Vertical Farming — No Longer a Futuristic Concept", org: "USDA ARS", sector: "cities", ev: "direct" },
  ];

  return { SECTORS, CHEMICALS, UNIT_OPS, BOTTLENECKS, STACK, PATHWAYS, ENTRIES, FEATURED, SOURCES };
})();
